In [210]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [211]:
import pandas as pd

df_neg = pd.read_csv('../EMOVO/ANALISI/Features/su_segnale_normalizzato/EMOVO_feat_eGeMAPSv02_neg.csv',
                     index_col=None,
                     header=0)
df_neg.head()

,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2,F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope,F0semitoneFrom27.5Hz_sma3nz_stddevRisingSlope,F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope,F0semitoneFrom27.5Hz_sma3nz_stddevFallingSlope,...,slopeUV0-500_sma3nz_amean,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp
0,37.525300,0.050403,36.458904,37.152824,39.463623,3.004719,38.333893,0.000000,14.896774,0.00000,...,0.060978,-0.006997,4.020675,2.816901,2.508961,0.047143,0.023123,0.288750,0.266150,-10.274729
1,37.071312,0.162663,30.914810,38.988010,42.993860,12.079048,241.764940,212.061630,162.454540,215.96207,...,0.060848,-0.006132,4.597124,3.873239,3.225807,0.093333,0.088944,0.194444,0.156639,-9.242617
2,40.402885,0.135318,36.010230,39.940050,41.917473,5.907242,25.699047,36.108288,192.437910,128.51425,...,0.033949,-0.002272,6.251621,4.219410,4.310345,0.104000,0.103073,0.097273,0.069294,-8.691848
3,34.926434,0.224606,34.170456,36.433006,41.556050,7.385593,156.930330,76.216324,205.114180,121.88782,...,0.051459,-0.006674,4.868939,4.040404,4.166667,0.047500,0.046837,0.171250,0.170106,-10.627707
4,37.364850,0.129435,33.772804,37.853207,39.901016,6.128212,46.746730,23.825377,-103.710050,114.59608,...,0.041583,-0.007661,4.801579,3.971119,4.044117,0.050909,0.034233,0.174545,0.185294,-9.613606

In [212]:
df_labels = pd.read_csv('../EMOVO/ANALISI/Labels/EMOVO_label_eGeMAPSv02_neg.csv', header=0)
df_labels.head()

  emotion  sentiment sex subjectId utteranceId
0     dis         -1   f        f1          b1
1     dis         -1   f        f1          b2
2     dis         -1   f        f1          b3
3     dis         -1   f        f1          d1
4     dis         -1   f        f1          d2

In [213]:
df = pd.concat([df_neg, df_labels], axis=1)
df.head()

,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2,F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope,F0semitoneFrom27.5Hz_sma3nz_stddevRisingSlope,F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope,F0semitoneFrom27.5Hz_sma3nz_stddevFallingSlope,...,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp,emotion,sentiment,sex,subjectId,utteranceId
0,37.525300,0.050403,36.458904,37.152824,39.463623,3.004719,38.333893,0.000000,14.896774,0.00000,...,0.047143,0.023123,0.288750,0.266150,-10.274729,dis,-1,f,f1,b1
1,37.071312,0.162663,30.914810,38.988010,42.993860,12.079048,241.764940,212.061630,162.454540,215.96207,...,0.093333,0.088944,0.194444,0.156639,-9.242617,dis,-1,f,f1,b2
2,40.402885,0.135318,36.010230,39.940050,41.917473,5.907242,25.699047,36.108288,192.437910,128.51425,...,0.104000,0.103073,0.097273,0.069294,-8.691848,dis,-1,f,f1,b3
3,34.926434,0.224606,34.170456,36.433006,41.556050,7.385593,156.930330,76.216324,205.114180,121.88782,...,0.047500,0.046837,0.171250,0.170106,-10.627707,dis,-1,f,f1,d1
4,37.364850,0.129435,33.772804,37.853207,39.901016,6.128212,46.746730,23.825377,-103.710050,114.59608,...,0.050909,0.034233,0.174545,0.185294,-9.613606,dis,-1,f,f1,d2

since i only want rows labelled as tri, rab i drop all the rows that dont cointain those labels, the resultig df should have 
168 rows

In [214]:
labels = ['tri','rab']
df = df[df['emotion'].isin(labels)]


df.head()

,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2,F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope,F0semitoneFrom27.5Hz_sma3nz_stddevRisingSlope,F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope,F0semitoneFrom27.5Hz_sma3nz_stddevFallingSlope,...,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp,emotion,sentiment,sex,subjectId,utteranceId
28,35.765182,0.125616,33.769470,34.533134,38.484000,4.714531,130.018390,112.377030,51.233772,3.428797,...,0.085714,0.034166,0.140000,0.079283,-9.784463,rab,-1,f,f1,b1
29,33.334496,0.122412,30.917048,35.043747,36.754670,5.837622,35.829105,35.900540,219.476180,170.219480,...,0.048571,0.035225,0.186250,0.084844,-8.311496,rab,-1,f,f1,b2
30,35.819820,0.123990,32.317265,37.509070,39.486427,7.169163,156.637570,230.999860,41.025463,2.994251,...,0.111111,0.069991,0.086667,0.045461,-9.029480,rab,-1,f,f1,b3
31,36.034454,0.126719,31.102016,36.488525,41.533485,10.431469,29.756440,9.325295,247.530460,278.394260,...,0.067143,0.056243,0.115000,0.101735,-9.618659,rab,-1,f,f1,d1
32,36.847065,0.078186,34.715313,36.550213,39.264797,4.549484,76.567940,71.099686,167.398320,181.194640,...,0.100000,0.097365,0.174000,0.060860,-8.640859,rab,-1,f,f1,d2

In [215]:
df.shape

(168, 93)

In [216]:
df_pos = pd.read_csv('../EMOVO/ANALISI/Features/su_segnale_normalizzato/EMOVO_feat_eGeMAPSv02_pos.csv',
                     index_col=None,
                     header=0)
df_labels_pos = pd.read_csv('../EMOVO/ANALISI/Labels/EMOVO_label_eGeMAPSv02_pos.csv', header=0)
df_pos_labeled = pd.concat([df_pos, df_labels_pos], axis=1)
df_pos_labeled.head()
df_pos_labeled.shape

(84, 93)

In [217]:
df_neu = pd.read_csv('../EMOVO/ANALISI/Features/su_segnale_normalizzato/EMOVO_feat_eGeMAPSv02_neu.csv', header=0)
df_labels_neu = pd.read_csv('../EMOVO/ANALISI/Labels/EMOVO_label_eGeMAPSv02_neu.csv', header=0)
df_neu_labeled = pd.concat([df_neu, df_labels_neu], axis=1)
df_neu_labeled.head()
df_neu_labeled.shape

(84, 93)

In [218]:
df_complete = pd.concat([df, df_pos_labeled, df_neu_labeled],ignore_index=True, axis=0)
columns_to_drop = ['sentiment', 'subjectId', 'utteranceId', 'sex']
df_complete.drop(columns=columns_to_drop, inplace=True)
df_complete.shape
df_complete.head()

,F0semitoneFrom27.5Hz_sma3nz_amean,F0semitoneFrom27.5Hz_sma3nz_stddevNorm,F0semitoneFrom27.5Hz_sma3nz_percentile20.0,F0semitoneFrom27.5Hz_sma3nz_percentile50.0,F0semitoneFrom27.5Hz_sma3nz_percentile80.0,F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2,F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope,F0semitoneFrom27.5Hz_sma3nz_stddevRisingSlope,F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope,F0semitoneFrom27.5Hz_sma3nz_stddevFallingSlope,...,slopeUV500-1500_sma3nz_amean,spectralFluxUV_sma3nz_amean,loudnessPeaksPerSec,VoicedSegmentsPerSec,MeanVoicedSegmentLengthSec,StddevVoicedSegmentLengthSec,MeanUnvoicedSegmentLength,StddevUnvoicedSegmentLength,equivalentSoundLevel_dBp,emotion
0,35.765182,0.125616,33.769470,34.533134,38.484000,4.714531,130.018390,112.377030,51.233772,3.428797,...,-0.008062,4.511647,4.494382,4.046243,0.085714,0.034166,0.140000,0.079283,-9.784463,rab
1,33.334496,0.122412,30.917048,35.043747,36.754670,5.837622,35.829105,35.900540,219.476180,170.219480,...,-0.008399,6.842672,5.418719,3.535354,0.048571,0.035225,0.186250,0.084844,-8.311496,rab
2,35.819820,0.123990,32.317265,37.509070,39.486427,7.169163,156.637570,230.999860,41.025463,2.994251,...,-0.006131,4.700423,3.940887,4.545455,0.111111,0.069991,0.086667,0.045461,-9.029480,rab
3,36.034454,0.126719,31.102016,36.488525,41.533485,10.431469,29.756440,9.325295,247.530460,278.394260,...,-0.005578,6.074678,5.590062,4.545454,0.067143,0.056243,0.115000,0.101735,-9.618659,rab
4,36.847065,0.078186,34.715313,36.550213,39.264797,4.549484,76.567940,71.099686,167.398320,181.194640,...,-0.008606,8.533515,5.228758,3.401361,0.100000,0.097365,0.174000,0.060860,-8.640859,rab

In [219]:
nan_indices = df_complete[df_complete.isna().any(axis=1)].index
nan_indices

Index([], dtype='int64')

In [220]:
def evaluate_model(model, x_test, y_test, averageM = 'macro'):
    from sklearn import metrics
    # Predict Test Data
    y_pred = model.predict(x_test)
    # Calculate accuracy, precision, recall, f1-score, and kappa score
    acc = metrics.accuracy_score(y_test, y_pred)
    prec = metrics.precision_score(y_test, y_pred, average = averageM)
    rec = metrics.recall_score(y_test, y_pred, average=averageM)
    f1 = metrics.f1_score(y_test, y_pred, average=averageM)
    kappa = metrics.cohen_kappa_score(y_test, y_pred, weights='quadratic')
    cm = metrics.confusion_matrix(y_test, y_pred)
    return {'acc': acc, 'prec': prec, 'rec': rec, 'f1': f1, 'kappa': kappa, 'cm': cm}

In [221]:

from sklearn.model_selection import train_test_split
from sklearn.neighbors import  KNeighborsClassifier

In [222]:
from sklearn.model_selection import train_test_split
#split dataset into train and test data

X_train, X_test, y_train, y_test = train_test_split(df_complete.iloc[:, :-1], df_complete['emotion'], test_size=0.2, random_state=42)

In [223]:
# create a knn classifier algorithm with 30 neighbors
knn = KNeighborsClassifier(n_neighbors=30, metric='euclidean')
# fit the model
knn.fit(X_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=30)

In [224]:
dtc_eval = evaluate_model(knn, X_test, y_test, averageM='macro')
dtc_eval

{'acc': 0.39705882352941174,
 'prec': 0.47206672637707126,
 'rec': 0.42879256965944273,
 'f1': 0.3948170731707317,
 'kappa': 0.21661442006269593,
 'cm': array([[9, 2, 0, 1],
        [8, 8, 1, 2],
        [5, 5, 5, 2],
        [7, 7, 1, 5]], dtype=int64)}

low perfomance, so we try to select the most significative features

In [225]:
from sklearn.feature_selection import VarianceThreshold
X = df_complete.iloc[:, :-1]
sel = VarianceThreshold(threshold=(.8 * (1 - .8)))
X_filtered = sel.fit_transform(X)
X.shape, X_filtered.shape

((336, 88), (336, 63))

we retry after this step of feature selection

In [226]:
X_train, X_test, y_train, y_test = train_test_split(X_filtered, df_complete['emotion'], test_size=0.2, random_state=42)
neigh = KNeighborsClassifier(n_neighbors=30, metric='euclidean')
neigh.fit(X_train, y_train)
dtc_eval = evaluate_model(neigh, X_test, y_test, averageM='macro')
dtc_eval

{'acc': 0.39705882352941174,
 'prec': 0.47206672637707126,
 'rec': 0.42879256965944273,
 'f1': 0.3948170731707317,
 'kappa': 0.21661442006269593,
 'cm': array([[9, 2, 0, 1],
        [8, 8, 1, 2],
        [5, 5, 5, 2],
        [7, 7, 1, 5]], dtype=int64)}

no results? try again filtering deeper

In [227]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif

In [239]:
X_new = SelectKBest(f_classif, k=7).fit(X, df_complete['emotion'])
X_new.get_feature_names_out()

array(['mfcc2_sma3_amean', 'F2amplitudeLogRelF0_sma3nz_stddevNorm',
       'F3amplitudeLogRelF0_sma3nz_stddevNorm',
       'slopeV0-500_sma3nz_amean', 'mfcc2V_sma3nz_amean',
       'alphaRatioUV_sma3nz_amean', 'hammarbergIndexUV_sma3nz_amean'],
      dtype=object)

In [240]:
X_train, X_test, y_train, y_test = train_test_split(X_new.transform(X), df_complete['emotion'], test_size=0.2, random_state=42)
neigh = KNeighborsClassifier(n_neighbors=30, metric='euclidean')
neigh.fit(X_train, y_train)
dtc_eval = evaluate_model(neigh, X_test, y_test, averageM='macro')
dtc_eval

{'acc': 0.5147058823529411,
 'prec': 0.5700067476383266,
 'rec': 0.529282765737874,
 'f1': 0.5226242690058479,
 'kappa': 0.36649475960738653,
 'cm': array([[ 8,  3,  0,  1],
        [ 6,  8,  4,  1],
        [ 6,  2,  9,  0],
        [ 4,  6,  0, 10]], dtype=int64)}

now we try with parameter optimization

In [231]:
from sklearn.model_selection import GridSearchCV
estimator_KNN = KNeighborsClassifier(algorithm='auto')
parameters_KNN = {
    'n_neighbors': (1,100, 1),
    'leaf_size': (10,100,1),
    'p': (1,2,3),
    'weights': ('uniform', 'distance'),
    'metric': ('minkowski', 'chebyshev', 'manhattan'),
}
                   
# with GridSearch
grid_search_KNN = GridSearchCV(
    estimator=estimator_KNN,
    param_grid=parameters_KNN,
    scoring = 'accuracy',
    n_jobs = -1,
    cv = 10
)

knn_optimized = grid_search_KNN.fit(X_train, y_train)
print(grid_search_KNN.best_params_)
dtc_eval = evaluate_model(knn_optimized, X_test, y_test, averageM='macro')
dtc_eval

{'leaf_size': 10, 'metric': 'minkowski', 'n_neighbors': 100, 'p': 1, 'weights': 'distance'}

{'acc': 0.5441176470588235,
 'prec': 0.5679563492063492,
 'rec': 0.5483875128998967,
 'f1': 0.539497264667044,
 'kappa': 0.49617590822179736,
 'cm': array([[ 7,  3,  1,  1],
        [10,  5,  2,  2],
        [ 4,  1, 11,  1],
        [ 3,  3,  0, 14]], dtype=int64)}